version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: lms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: lms_db
    ports:
      - "3307:3306"
    volumes:
      - lms-data:/var/lib/mysql
      # Mount the SQL file only if it exists
      - ./database/lms_db_dump.sql:/docker-entrypoint-initdb.d/lms_db_dump.sql:ro

  backend:
    build: ./backend
    container_name: lms-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/lms_db
      DB_USER: root
      DB_PASSWORD: root123

volumes:
  lms-data:
